language: cpp
python: 3.7
dist: xenial
sudo: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-7
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - libstdc++-7-dev
            - clang-7
            - valgrind
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libpng-dev
            - valgrind
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - LINKER_FLAGS=""

before_install:
  - eval "${MATRIX_EVAL}"

script:
  # set( CMAKE_CXX_STANDARD 17 ) support is required, so let's just build one of the latest CMake releases.
  - version=3.14
  - build=3
  - mkdir temp
  - cd temp
  - wget https://cmake.org/files/v$version/cmake-$version.$build.tar.gz
  - tar -xzvf cmake-$version.$build.tar.gz
  - cd cmake-$version.$build/
  - mkdir build && cd build
  - cmake ..
  - sudo make install
  - cd ../../..
  # Build the CMakeSL
  - mkdir build && cd build
  - cmake .. -DCMAKESL_WITH_TESTS=ON -DCMAKESL_WITH_TOOLS=ON -DCMAKESL_WITH_EXAMPLES=ON
  - make
  - ctest -D ContinousMemCheck
